module.exports = [
	{
		icon: "home",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#f1c40f",
	},
	{
		icon: "coins",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#e67e22",
	},
	{
		icon: "umbrella-beach",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#3498db",
	},
	{
		icon: "gas-pump",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#9b59b6"
	},
	{
		icon: "cloud-rain",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#7f8c8d",
	},
	{
		icon: "gifts",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#27ae60",
	},
	{
		icon: "receipt",
		prefix: "fas",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#008D8E",
	},
	{
		icon: "playstation",
		prefix: "fab",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#003087",
	},
	{
		icon: "xbox",
		prefix: "fab",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#52b043",
	},
	{
		icon: "steam",
		prefix: "fab",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#333333",
	},
	{
		icon: 'dropbox',
    	prefix: 'fab',
    	size: 100,
		color: '#f7f7f7',
		backgroundColor: '#007ee5',
    },
	{
		icon: "cc-amex",
		prefix: "fab",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#4d4f53",
	}
]