module.exports = [
	{
		icon: "home",
		prefix: "fa-solid",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#f1c40f",
	},
	{
		icon: "umbrella-beach",
		prefix: "fa-solid",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#3498db",
	},
	{
		icon: "gas-pump",
		prefix: "fa-solid",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#9b59b6"
	},
	{
		icon: "gifts",
		prefix: "fa-solid",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#27ae60",
	},
	{
		icon: "hmrc",
		prefix: "simpleicons",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#008D8E",
	},
	{
		icon: "playstation",
		prefix: "fa-brands",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#003087",
	},
	{
		icon: "xbox",
		prefix: "fa-brands",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#52b043",
	},
	{
		icon: "steam",
		prefix: "fa-brands",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#333333",
	},
	{
		icon: 'dropbox',
    	prefix: 'fa-brands',
    	size: 100,
		color: '#f7f7f7',
		backgroundColor: '#007ee5',
    },
	{
		icon: "cc-amex",
		prefix: "fa-brands",
		size: 100,
		color: "#f7f7f7",
		backgroundColor: "#4d4f53",
	},
	{
		icon: 'patreon',
		prefix: 'simpleicons',
		size: 100,
		color: '#f7f7f7',
		backgroundColor: '#f96854',
	},
	{
		icon: 'lamborghini',
		prefix: 'simpleicons',
		size: 100,
		color: '#f7f7f7',
		backgroundColor: '#ddb321',
	},
	{
		icon: 'rollsroyce',
		prefix: 'simpleicons',
		size: 100,
		color: '#f7f7f7',
		backgroundColor: '#680021',
	},
	{
		icon: 'monzo',
		prefix: 'simpleicons',
		size: 100,
		color: '#f7f7f7',
		backgroundColor: '#fe4d59',
	},
]